---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitolite-data
  namespace: gitolite
  labels:
    app: gitolite
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 8Gi
  storageClassName: rook-cephfs
