apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: gitolite
  namespace: gitolite
spec:
  virtualhost:
    fqdn: git.this-is-fine.io
    tls:
      passthrough: true
  tcpproxy:
    services:
    - name: gitolite
      port: 22
